### ISSUE TITLE
Consider new CloudFlare APIs

### ISSUE THREAD

**Issue by pencoyd** [daniel-middleton/CloudFlare-DDNS-Agent#1]
https://api.cloudflare.com details our new APIs, currently working and being added to.

The current API you're using will be supported for a significant amount of time, but encourage all new development to consider the new APIs.

FYI... https://www.cloudflare.com/trademark

Thanks,
John
CloudFlare
(if need anything privately, first name at cloudflaredotcom)

**Comment by monokal** [comment]
Thank you @pencoyd, I'll definitely take a look at the new APIs and as always I welcome and further suggestions or contributions.
